### ISSUE TITLE
Date and times are not properly indexed

### ISSUE THREAD

**Issue by cdevienne** [plone/guillotina_elasticsearch#29]
The indexer uses DefaultCatalogDataAdapter to prepare the documents.
Because this adapter rely on json_compatible, all the dates and times (and probably other datatypes) are converted to simple strings, which prevent any use of the date math or even simply compare dates in a range filter.

**Comment by vangheem** [comment]
Can you give an example? I'm not sure I understand how you'd prefer the data be serialized.

Have you tried customizing the DefaultCatalogDataAdapter?

**Comment by vangheem** [comment]
the data needs to be json. How else should it be serialized?

**Comment by cdevienne** [comment]
I have not yet modified the adapter (will do though).

The python api of elasticsearch can be given datetime or date objects. see [this example](https://elasticsearch-py.readthedocs.io/en/master/#example-usage).

All the attempts to use [date math](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math) I made failed. The range is simply not working. And the only logical explanation is that elastic search does not know that my field is a date. Hence my conclusion on the DataAdapter.

**Comment by vangheem** [comment]
But if it is a date, shouldn't it be serialized to a date? I'm not sure how you'd want it indexed to something different?

Yes, elasticsearch py has support for python date objects. That's just because it's running it's own serializer--a serializer that basically the same as what guillotina is doing. See: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/serializer.py#L28

It's just converting it to a string. It needs to be in a date string format--this is json.

Are you maybe confusing indexing with querying?

What are you trying to store? And then, what are you trying to search by?

**Comment by cdevienne** [comment]
Indeed, I am mistaken somewhere.

What I am trying is to filter a date with range.
Something like `"range": {"start_date": {"gte": "<SOMEDATE>"}}`.
But the returned object "start_date" do not match the condition at all, even though the "range" is in a "filter" then a "must".

**Comment by vangheem** [comment]
couple things to think about...

1. the search endpoint modifies the query to filter out things you don't have permission to. You might want to see what the raw query is better sent(I believe log level can help here as g_elasticsearch logs debug the query)
2. I usually like to work out my queries manually first in postman to make sure they work.

**Comment by cdevienne** [comment]
It is basically what I did, and I could not find how to filter by date... Will try again tomorrow.

**Comment by cdevienne** [comment]
I just checked the actual mapping, and I have : 

```json
"start_date": {
    "type": "text"
}
```

although my start_date field is defined as:
```python
start_date = schema.Date(title=_('start date'))
```

So my range queries have no chance to work. How can I fix this ?

**Comment by cdevienne** [comment]
I just realize that 'index()' takes a 'type' kwarg... The lack of documentation is sometimes very frustrating!

**Comment by vangheem** [comment]
Yes, it's my main goal for the July sprint
