### ISSUE TITLE
Index mappings for each content-type in a dedicated document in ES

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina_elasticsearch#43]
Lets say I have a content type`tweet` and `comment`. Both content types have a field 'msg'. I want to index the field 'msg' as 'text' in both content types but use different analyzers for each content type. I have something like this:

Tweet:
```python
index_field('msg', field_mapping={
        'type': 'text',
        'analyzer': 'name_analyzer',
    })
msg = schema.Text()
```

Comment:
```python
index_field('msg', field_mapping={
        'type': 'text',  # Or even a different type!
    })
msg = schema.Text()
```

Is there any way to do something like `index_field('msg', doc='tweet', field_mapping={...})`?

Thank you in advance!

**Comment by bloodbare** [comment]
Elasticsearch does not know about doctypes and flattens all the fields, the best aproach is to define at the indexer different mapped fields for each field type.

**Comment by masipcat** [comment]
So, you mean something like `index_field('msg_tweet', ...)` and `index_field('msg_comment', ...)`? If that's the case, I was trying to avoid that :P

**Comment by bloodbare** [comment]
If you want to maintain the fields with the same name on the object you can use the indexer decorator to define two different indexes with different name. This is a limitation by ES afaik, the indexes on lucene are flattened:

https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html

**Comment by masipcat** [comment]
OK, thank you for the answer :) 

I think that guillotina_elasticsearch should fail or at least warn the user that is creating two indices with same name but different mapping

**Comment by masipcat** [comment]
Hello again! I have a couple of questions/suggestion somehow related with this issue:

1. How can I choose which schemas are indexed and which aren't (right now all the base fields of all schemas are indexed). 

2. I experienced the hard way what happens when I define a index that already was defined by another field in another schema (I tried to index the field `tags` in IMyContent but IDublinCore was providing a field mapping as well): sometimes it works, sometimes not... I'd suggest that `get_mappings()` fails when detects two index_name with different mappings. What do you think?

**Comment by masipcat** [comment]
I'd clarify the purpose of the point 1.

Let's say I have a tree of content like:

`/A/1`
`/A/2`
`/A/3`
`/B/1`

`A` and `B` are the main content. We want to retrieve from elasticsearch `A` with its children. We indexed the leafs de-normalized (for performance and simplicity). That's why indexing leafs in its own document is "wasting" resources.

**Comment by bloodbare** [comment]
Abount point 2, I have some use case were different Schemas serialize the same field on the object, so maybe could be a warning on bootstrap.

About point 1, If you want subojects that are not indexed they should be on annotations and not on the main tree

**Comment by masipcat** [comment]
> Abount point 2, I have some use case were different Schemas serialize the same field on the object, so maybe could be a warning on bootstrap.

Same field with same mapping? If that's the case, `get_mappings()` won't complain. It will only raise the exception when you are defining same mapping more than once with different values, to prevent unknown behaviours from developer's point of view. But if you want, I can replace the exception with a warning.

> About point 1, If you want subjects that are not indexed they should be on annotations and not on the main tree

I'll try this way ;)

Thank you!
