### ISSUE TITLE
TIDConflicts when using g_es + g_batch + g_rediscache

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina_elasticsearch#45]
I found a bug when using `guillotina_batch` (eager_commit = True) + `guillotina_elasticsearch` + `guillotina_rediscache`. I don't know if it could happen as well with `guillotina_batch` (eager_commit = False).

Steps to reproduce:

1. Call `@batch` to create object A and B -> works
2. Call `@batch` to create object C and D -> works
3. Call `@batch` to update object A and B -> fails with `TIDConflcit`
4. Call again the previous endpoint -> fails with `TIDConflcit` (never recovers)

Guillotina should clear the cache after `TIDConflict` but is not working. After investigating all the morning, I found why is not working: https://github.com/guillotinaweb/guillotina_elasticsearch/blob/master/guillotina_elasticsearch/migration.py#L157

Any thoughts on how to fix this issue? Is it safe to delete this line? I commented it and solved the problem.

Thank you in advance!

**Comment by masipcat** [comment]
I forget to say that guillotina_elasticsearch stores the document despite not being updated in postgresql:

```
Error on execution of view 248b28481a7c47a5b65765130af5f7db
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/guillotina_batch/api.py", line 197, in _handle
    await request._tm.commit(request)
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction_manager.py", line 99, in commit
    return await shield(self._commit(request=request, txn=txn))
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction_manager.py", line 108, in _commit
    await txn.commit()
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction.py", line 304, in commit
    return await self._commit()
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction.py", line 320, in _commit
    await self.tpc_commit()
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction.py", line 380, in tpc_commit
    await self._store_object(obj, oid)
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction.py", line 366, in _store_object
    await self._manager._storage.store(oid, serial, writer, obj, self)
  File "/usr/local/lib/python3.7/site-packages/guillotina/db/storages/pg.py", line 632, in store
    oid, txn, old_serial, writer)
guillotina.exceptions.TIDConflictError: Mismatch of tid of object being updated. This is likely caused by a cache invalidation race condition and should be an edge case. This should resolve on request retry..
Object ID: 3ee|4ba|846|576|f3d39c09bf5e4fc59181fcd03293dfa6
TID: 12240
Old Object TID: 10067
Belongs to: None
Parent ID: 75-2009
Retries: 0/3
ES Query: {"took": 3, "errors": false, "items": [{"update": {"_index": "api-db-guillotina_9", "_type": "doc", "_id": "3ee|4ba|846|576|f3d39c09bf5e4fc59181fcd03293dfa6", "_version": 15, "result": "updated", "_shards": {"total": 2, "successful": 1, "failed": 0}, "_seq_no": 2409, "_primary_term": 1, "status": 200}}]}
```

**Comment by vangheem** [comment]
what the heck!!! https://github.com/guillotinaweb/guillotina_elasticsearch/blob/master/guillotina_elasticsearch/migration.py#L157

I imagine that was an optimization for doing migrations with commands but ouch, that's too bad.

So also, I think guillotina_batch should handle conflict errors and do retries like regular request handlers do.

**Comment by vangheem** [comment]
And the reason is that regular conflicts cause the value to be invalidated(or should).

**Comment by vangheem** [comment]
I imagine the whole eager_commit behavior needs to behavior more like the request commit handler logic in order to properly handle these types of requests

**Comment by masipcat** [comment]
I've been doing more research on this because I didn't understand why the migrator was being called... And I think I found the answer.

I have configured a subscriber for some resources that when `IObject(Added|Modified)Event` is fired I reindex the content of another object. I use this code to reindex the other object:
```python
...
util = query_utility(ICatalogUtility)
await util.reindex_all_content(parent)  # interanally creates a instance of Reindexer (that inherits from Migrator).
```
Now it's clear why this line (https://github.com/guillotinaweb/guillotina_elasticsearch/blob/master/guillotina_elasticsearch/migration.py#L157) was affecting the whole thing...

So, is `reindex_all_content()` only intended to be used in migrations or can be called as part of the application logic? If it's the last case, I think the Migrator shouldn't modify the `request.cache` or should restore the original value when the reindexation is done.

What do you think?

PS: At the end it seems that this problem is not related to guillotina_batch, it could happen with a normal request, but I'll do a PR that handles conflict errors

**Comment by vangheem** [comment]
It's part of logic when you change sharing settings which affect all children. It reindexes the entire tree below that node.

If you just want to index one object, you should use https://github.com/plone/guillotina/blob/master/guillotina/catalog/index.py#L133

**Comment by masipcat** [comment]
Thank you! I fixed my code with `index_object()`.

But I'm a bit worried because of `request._txn._cache = DummyCache()`.

So I created some "real-world" tests to try to convince you:

**Test 1**
- `POST @batch?eager-commit=true`
   - `POST /A` ~> 201
   - `POST /B` ~> 201
   - `POST /A/@sharing` ~> 200
   - `POST /B/@sharing` ~> 200

"Everything works as expected"

- `GET /A/@sharing`
```json
{
    ...
    "local": {
		"prinperm": {
			"user1": {
				"guillotina.AccessContent": "AllowSingle"
			}
		},
		"prinrole": {
			"root": {
				"guillotina.Owner": "Allow"
			}
		},
		"roleperm": {}
	}
}
```
- `GET /B/@sharing`
```json
{
    ...
    "local": {
		"prinperm": {},
		"prinrole": {
			"root": {
				"guillotina.Owner": "Allow"
			}
		},
		"roleperm": {}
	}
}
```

Permissions for **user1** missing! This could be a security issue, right?

-------------
**Test 2**

Now I do the same operations in a different order:

- `POST @batch?eager-commit=true`
   - `POST /A`  ~> 201
   - `POST /A/@sharing` ~> 200
   - `POST /B` ~> 201
   - `POST /B/@sharing` ~>  **404!**

This shouldn't fail, like in test 1.

----------

I guess you disable cache when doing a migration of the entire catalog to avoid fill/invalidate the cache with the whole database, but I think we shouldn't do this when reindexing security (or any other operation in the application logic).

I would suggest to add the kw argument `cache` to Migrator (`Migrator(cache=True)`). And when running migrations / reindex as commands we set explicitly `cache=False`.

Thoughts?

**Comment by vangheem** [comment]
`@sharing` doesn't do anything with ES/catalog though so the fact that it's missing means something worse is going on with batch eager commit I think.

`I would suggest to add the kw argument cache to Migrator (Migrator(cache=True)` -- I agree!

**Comment by masipcat** [comment]
> `@sharing` doesn't do anything with ES/catalog though so the fact that it's missing means something worse is going on with batch eager commit I think.

POST `@sharing` calls `apply_sharings()` (https://github.com/plone/guillotina/blob/fc44efff0c3f62adbb49d031f2c9591ad916c6ec/guillotina/api/content.py#L405) and send a `notify(IObjectPermissionsModifiedEvent)` (https://github.com/plone/guillotina/blob/5e61abe6a8bf5a9f0e546b04c28b335d550c9152/guillotina/security/utils.py#L206) that triggers `reindex_in_future()` (https://github.com/plone/guillotina/blob/8244d9ade667a2cd8a0f7a34d2e4a45b2f2b13cb/guillotina/catalog/index.py#L76).

> `I would suggest to add the kw argument cache to Migrator (Migrator(cache=True)` -- I agree!
Do you mind if I open a PR to change this?

**Comment by vangheem** [comment]
sorry, I mean in your example with `GET /B/@sharing` -- that has nothing to do with catalog.

**Comment by vangheem** [comment]
And yes please, open a PR!

**Comment by masipcat** [comment]
> sorry, I mean in your example with GET /B/@sharing -- that has nothing to do with catalog.

The problem with `GET /B/@sharing` is that is returning the permissions from the redis cache but the cache for B is stale. Here is why:

**Test 1**
- `POST @batch?eager-commit=true`
   - `POST /A` ~> 201 (Update rediscache)
   - `POST /B` ~> 201 (Update rediscache)
   - `POST /A/@sharing` ~> 200 (Update rediscache and reindexer changes cache to DummyChache)
   - `POST /B/@sharing` ~> 200 (Updates dummycache)

` GET /A/@sharing` (result from rediscache)
` GET /B/@sharing` (result from rediscache but doesn't contain changes in `@sharing`)
